namespace ManiaExchange.Api.Enums;

public enum TmxMapSearchOrder
{
    MapNameAscending = 0,
    UploaderUsernameAscending = 1,
    MapUploadDateNewest = 2,
    MapUploadDateOldest = 3,
    MapLastUpdatedNewest = 4,
    MapLastUpdatedOldest = 5,
    MapActivityNewest = 6,
    MapActivityOldest = 7,
    MapAwardCountMost = 8,
    MapAwardCountLeast = 9,
    MapCommentsMost = 10,
    MapCommentsLeast = 11,
    MapDifficultyEasiest = 12,
    MapDifficultyOldest = 13,
    MapLengthShortest = 14,
    MapLengthLongest = 15,
    MapDownloadsLeast = 16,
    MapDownloadsMost = 17,
    MapDownloadDateNewest = 18,
    MapDownloadDateOldest = 19,
    MapAwardDateNewest = 20,
    MapAwardDateOldest = 21,
    MapReplaySubmitDateNewest = 22,
    MapReplaySubmitDateOldest = 23,
    MapLeaderboardValueLowest = 24,
    MapLeaderboardValueHighest = 25,
    MapMxKarmaRatingLowest = 26,
    MapMxKarmaRatingHighest = 27,
    MapAuthorTimeLowest = 28,
    MapAuthorTimeHighest = 29,
    MapMxWorldRecordTimeLowest = 30,
    MapMxWorldRecordTimeHighest = 31,
    MapVideoSubmittedNewest = 32,
    MapVideoSubmittedOldest = 33
}